(function(){function g(a){var c={};a=a.split(",");for(var d=0;d<a.length;d++)c[a[d]]=!0;return c}var m=/^<([-A-Za-z0-9_]+)((?:\s+\w+(?:\s*=\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,v=/^<\/([-A-Za-z0-9_:]+)[^>]*>/,x=/([-A-Za-z0-9_]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,u=/^<([-A-Za-z0-9_:-]+)((?:\s+[a-zA-Z_0-9:-]+(?:\s*=\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,y=/([-A-Za-z0-9_:-]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,
z=g("colgroup,col"),A=g("area,base,basefont,br,col,frame,hr,img,input,isindex,link,meta,param,embed");g("area,base,basefont,br,col,frame,img,input,isindex,link,meta,param,embed");var B=g("address,applet,blockquote,button,center,dd,del,dir,div,dl,dt,fieldset,form,frameset,hr,iframe,ins,isindex,li,map,menu,noframes,noscript,object,ol,p,pre,script,table,tbody,td,tfoot,th,thead,tr,ul,h1,h2,h3,h4,h5,h6,figure"),w=g("a,abbr,acronym,applet,b,basefont,bdo,big,br,button,cite,code,del,dfn,em,font,i,iframe,img,input,ins,kbd,label,map,object,q,s,samp,script,select,small,span,strike,strong,sub,sup,textarea,tt,u,var"),
C=g("colgroup,dd,dt,li,options,p,td,tfoot,th,thead,tr"),D=g("checked,compact,declare,defer,disabled,ismap,multiple,nohref,noresize,noshade,nowrap,readonly,selected"),E=g("");"undefined"==typeof DEXT5_EDITOR&&(DEXT5_EDITOR={});DEXT5_EDITOR.HTMLParser=function(a,c,d){function t(a,b,h,p){b=b.toLowerCase();if(B[b]){for("table"!=e.last()&&"tbody"!=e.last()||"td"!=b||t("","tr","","");e.last()&&w[e.last()];)q("",e.last());"p"!=e.last()||"table"!=b&&"hr"!=b&&"center"!=b&&"figure"!=b||q("","p")}C[b]&&e.last()==
b&&q("",b);(p=A[b]||!!p)||e.push(b);if(d.start){var f=[];a=m.test(a)?x:y;h.replace(a,function(a,b,h,d,p){h=h?h:d?d:p?p:D[b]?b:"";d="";""!=a&&(a=a.substring(a.indexOf(b)+b.length),a=a.substring(a.indexOf("=")+1),a=a.replace(/^\s+/,""),d=a.substring(0,1),"'"!=d&&'"'!=d&&(d=""));f.push({name:b,value:h,escaped:h.replace(/(^|[^\\])"/g,'$1\\"'),quotationmark:d})});d.start&&d.start(b,f,p)}}function q(a,b){if(b)for(b=b.toLowerCase(),h=e.length-1;0<=h&&e[h]!=b;h--);else var h=0;if(0<=h){for(var p=e.length-
1;p>=h;p--)d.end&&d.end(e[p]);e.length=h}}var b,f,e=[],g=a;for(e.last=function(){return this[this.length-1]};a;){f=!0;if(e.last()&&E[e.last()])a=a.replace(new RegExp("(.*)</"+e.last()+"[^>]*>"),function(a,b){b=b.replace(/\x3c!--(.*?)--\x3e/g,"$1").replace(/<!\[CDATA\[(.*?)]]\x3e/g,"$1");d.chars&&d.chars(b);return""}),q("",e.last());else{var l=a.indexOf("<");b=a.indexOf(">")+1;var n=a.substring(l,b);if(0==a.indexOf("\x3c!--"))b=a.indexOf("--\x3e"),0<=b&&(d.comment&&d.comment(a.substring(4,b)),a=a.substring(b+
3),f=!1);else if(0==a.indexOf("<?xml"))b=a.indexOf("/>"),0<=b&&(a=a.substring(b+2),f=!1);else if(0!=a.indexOf("<")&&"</"+e.last()+">"==n.replace(/ /ig,""))f=a.substring(0,l),a=a.substring(b),a=f+"</"+e.last()+">"+a,f=!0;else if(0==a.indexOf("</")){if(b=a.match(v))a=a.substring(b[0].length),b[0].replace(v,q),f=!1}else if(0==a.indexOf("<"))if(b=a.match(m))a=a.substring(b[0].length),b[0].replace(m,t),f=!1;else if(b=a.match(u))a=a.substring(b[0].length),b[0].replace(u,t),f=!1;else if("1"==DEXTTOP.G_CURREDITOR._config.removeIncorrectAttribute&&
(b=a.indexOf("<"),n=a.indexOf(">"),0==b&&0<n)){var k=a.substring(0,n+1),r=l=b=0;0<k.indexOf('\ub9d1\uc740=""')?(b=k.indexOf('\ub9d1\uc740=""'),l=5,r=k.split('\ub9d1\uc740=""').length):0<k.indexOf("\ub9d1\uc740=''")&&(b=k.indexOf("\ub9d1\uc740=''"),l=5,r=k.split("\ub9d1\uc740=''").length);if(2==r&&0<b&&(n=a.substring(n+1),r=k.substring(0,b).lastIndexOf(" "),r<b+l))if(a=k.substring(r,b+l),k=k.replace(a,""),a=k+n,b=a.match(m))a=a.substring(b[0].length),b[0].replace(m,t),f=!1;else if(b=a.match(u))a=a.substring(b[0].length),
b[0].replace(u,t),f=!1}f&&(b=a.indexOf("<"),f=0>b?a:a.substring(0,b),a=0>b?"":a.substring(b),d.chars&&(e.last()&&w[e.last()]&&"textarea"!=e.last()&&"script"!=e.last()&&(b=!1,l=RegExp("\\S\\n","g"),l.test(f)&&(b=!0),l=RegExp("\\n\\S","g"),l.test(f)&&(b=!0),l=RegExp("\\S\\n\\S","g"),l.test(f)&&(b=!0),b?f=f.replace(/\n/g," "):(l=RegExp("\\n\\n","g"),l.test(f)&&""==f.trim()?f=f.replace(/\n\n/g,""):f==unescape("%20%20")&&(b=new RegExp(unescape("%20"),"g"),f=f.replace(b,"&nbsp;")))),c&&(b=new RegExp(unescape("%20%20"),
"g"),f=f.replace(b,"&nbsp; ")),d.chars(f)))}if(a==g)throw"Parse Error: "+a;g=a}q()};DEXT5_EDITOR.HTMLParser.HTMLtoXML=function(a,c){var d="";DEXT5_EDITOR.HTMLParser(a,c,{start:function(a,c,b){d+="<"+a;for(a=0;a<c.length;a++)d="href"==c[a].name||"src"==c[a].name?d+(" "+c[a].name+"="+c[a].quotationmark+c[a].value+c[a].quotationmark):""!=c[a].quotationmark?d+(" "+c[a].name+"="+c[a].quotationmark+c[a].value+c[a].quotationmark):d+(" "+c[a].name+'="'+c[a].escaped+'"');d+=(b?"/":"")+">"},end:function(a){z[a]||
(d+="</"+a+">")},chars:function(a){d+=a},comment:function(a){d="0"==DEXTTOP.G_CURREDITOR._config.removeComment?d+("\x3c!--"+a+"--\x3e"):d+""}});DEXTTOP.DEXT5.util.writeLog("DEBUG","HTMLParser.HTMLtoXML return - "+d,"","");return d};DEXT5_EDITOR.HTMLParser.RemoveOfficeTag=function(a,c){if(""==a||void 0==a)return DEXTTOP.DEXT5.util.writeLog("DEBUG","HTMLParser.RemoveOfficeTag return - ","",""),"";a=DEXT5_EDITOR.HTMLParser.RemoveOfficeTag2(a);a=DEXTTOP.DEXT5.util.replaceOneSpaceToNbsp(a);c&&(a=a.replace(/>\s+</g,
"><"));DEXTTOP.DEXT5.util.writeLog("DEBUG","HTMLParser.RemoveOfficeTag return - "+a,"","");return a};DEXT5_EDITOR.HTMLParser.RemoveOfficeTag2=function(a){var c=RegExp("<o:p></o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p>\\s+</o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p ([^>]+)></o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p ([^>]+)>\\s+</o:p>","gi");a=a.replace(c,"");a=a.replace(/\slang=[\"]?en-us[\"]?/gi,"");"1"==DEXTTOP.G_CURREDITOR._config.removeMsoClass&&(a=a.replace(/\sclass=[\"]?(mso)\w+[\"]?/gi,
""));a=a.replace(/&quot;/gi,"&quot_dext;");c=RegExp('mso-[^:]+:[^;">]+;',"gi");a=a.replace(c,"");c=RegExp('mso-[^:]+:[^;">]+("|\')',"gi");a=a.replace(c,"$1");a=a.replace(/&quot_dext;/gi,"&quot;");c=RegExp("<v:shapetype ([^>]+)>[\\s\\S]*?</v:shapetype>","gi");a=a.replace(c,"");c=RegExp("<v:shape [^>]+>[\\s\\S]*?(<img [^>]+>)*?</v:shape>","gi");a=a.replace(c,"$1");c=RegExp("<v:shape ([^>]+)>[\\s\\S]*?</v:shape>","gi");a=a.replace(c,"");a=a.replace(/<\!\[if ppt\]>/gi,"");DEXTTOP.DEXT5.util.writeLog("DEBUG",
"HTMLParser.RemoveOfficeTag2 return - "+a,"","");return a};DEXT5_EDITOR.HTMLParser.CleanNestedHtml=function(a,c,d){function g(a,b){for(var h=0,d=a.childNodes.length,c=0;c<d;c++)3!=a.childNodes[c].nodeType&&(b&&(h+=g(a.childNodes[c],b)),h++);return h}function q(a){for(var d="",h=Array(a.childNodes.length),c=0;c<h.length;c++){h[c]=[];h[c].push(a.childNodes[c]);b(a.childNodes[c],h[c]);var f=c,e=h[c],l=[],g=0;a:for(;g<e.length;g++){for(var k=0;k<l.length;k++)if(l[k]==e[g])continue a;l[l.length]=e[g]}h[f]=
l;d+=h[c].join("")}return d}function b(a,c){for(var d=a.childNodes,e=0;e<d.length;e++)c.push(d[e]),d[e].hasChildNodes()&&b(d[e],c);for(var d=0,g;d<c.length;d++){e=c[d];if(1==e.nodeType){g=e.nodeName;if(-1==(" "+l.join(" ").toUpperCase()+" ").search(" "+g.toUpperCase()+" ")){c.splice(d,1);d--;continue}g=e;for(var k="",n=0,m=void 0;n<g.attributes.length;n++)m=g.attributes[n],1==m.specified&&("style"==m.name?(m=f(g),""!=m&&(k+=' style="'+f(g)+'"')):""!=m.value&&(k+=" "+m.name+'="'+m.value+'"'));g=k;
e="<"+e.nodeName.toLowerCase()+g+">"}else 3==e.nodeType&&(e=e.nodeValue.replace(/\n/g,""));c[d]=e}return c}function f(a){for(var b="",c=0,d=m.length,e;c<d;c++)a.currentStyle?e=a.currentStyle[m[c]]:window.getComputedStyle&&(e=document.defaultView.getComputedStyle(a,null).getPropertyValue(m[c])),b+=m[c]+":"+e+";";return b}var e=50,m=[],l="p a abbr acronym applet b basefont bdo big br button cite code del dfn em font i iframe img input ins kbd label map object q s samp script select small strike strong sub sup textarea tt u var".split(" ");
"undefined"!=typeof d&&(e=parseInt(d));var n=a._DOC.getElementsByTagName("p");d=!1;for(var k=0,r=n.length;k<r;k++)if(g(n[k],!0)>e){d=!0;break}d&&(showProcessingBackground(),setTimeout(function(){a._BODY.contentEditable=!1;try{if("2"==c)DEXTTOP.DEXT5.DextCommands("select_all",a.ID),DEXTTOP.DEXT5.DextCommands("remove_css",a.ID),DEXTTOP.DEXT5.DextCommands("remove_format",a.ID),a._FRAMEWIN.setFocusToBody(),setTimeout(function(){a._FRAMEWIN.doSetCaretPosition(a._BODY.firstChild,0)},20);else for(var b=
0,d=n.length,f;b<d;b++)g(n[b],!0)>e&&(f=q(n[b]),f=DEXT5_EDITOR.HTMLParser.HTMLtoXML(f),n[b].innerHTML=f)}catch(k){}hideProcessingBackground();a._BODY.contentEditable=!0},G_Progress_LoadTime))};DEXT5_EDITOR.HTMLParser.makeMap=function(a){return g(a)}})();
